FROM debian:stable-slim@sha256:377ddc2a20fe8632a49b69dcfff10fccbd5b4f0b8c2d593420a6a5e03070dfa1

# Update package list and install necessary packages
RUN DEBIAN_FRONTEND=noninteractive; \
    apt-get update && \
    apt-get install -y --no-install-recommends openssh-server openssh-client && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -f /usr/bin/ssh-keyscan && \
    rm -f /usr/bin/ssh-keygen && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir /volume

# Copy scripts and configuration files
COPY entrypoint.sh /entrypoint.sh
COPY sshkey.sh /sshkey.sh
COPY sshd_config.privileged /etc/ssh/sshd_config

# Ensure scripts are executable
RUN chmod +x /entrypoint.sh /sshkey.sh

# Expose port
EXPOSE 2137

# Switch to root user
USER root

# Entrypoint
ENTRYPOINT ["/entrypoint.sh"]
