apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: busybox
      image: busybox:stable
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /mnt/test
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mounted-pvc
