name: "fuzz"
on:
  push:
  pull_request:
jobs:
  fuzz-test:
    name: Fuzz test
    runs-on: ubuntu-latest
    steps:
      - uses: jidicula/go-fuzz-action@v1.2.0
        with:
          packages: './...'
          fuzz-time: 30s
